Repository 979216944/checker-framework, pull requests merged in 2018-05, with the labels that each got.

#3 Mapkey boxing yk57
  README.md
  checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnalysis.java
  checker/src/main/java/org/checkerframework/checker/nullness/NullnessChecker.java
  checker/src/main/java/org/checkerframework/checker/nullness/NullnessTransfer.java
  checker/src/main/java/org/checkerframework/checker/nullness/nullness_lite.astub
  checker/src/test/java/tests/NullnessLiteOptTest.java
  checker/tests/nullness-liteoption/NullnessLiteBoxing1.java
  checker/tests/nullness-liteoption/NullnessLiteMapKey1.java
Labels: enhancement

#4 [Updates] KeyForSubChecker also disallows aliasing
  checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnalysis.java
  checker/src/main/java/org/checkerframework/checker/nullness/KeyForStore.java
Labels: enhancement

#10 Improve the Nullness_Lite Tests
  checker/tests/nullness-liteoption/NullnessLiteInit1.java
  checker/tests/nullness-liteoption/NullnessLiteInvalidDataflow1.java
Labels: help wanted

#9 Issue 5 bug fixed & individual commands added for NullnessLite
  checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnalysis.java
  checker/src/main/java/org/checkerframework/checker/nullness/KeyForStore.java
  checker/src/main/java/org/checkerframework/checker/nullness/KeyForSubchecker.java
  checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnalysis.java
  checker/src/main/java/org/checkerframework/checker/nullness/NullnessChecker.java
  checker/src/main/java/org/checkerframework/checker/nullness/NullnessStore.java
  checker/src/main/java/org/checkerframework/checker/nullness/NullnessTransfer.java
  checker/src/test/java/tests/NullnessLiteComRegTest.java
  checker/tests/nullness-liteoption-comreg/CommandLineShadowRegTest.java
  checker/tests/nullness-liteoption-comreg/README
  checker/tests/nullness-liteoption-comreg/issue5.astub
Labels: bug, enhancement

#13 Added test cases for each individual option to NullnessLite
  checker/src/test/java/tests/NullnessLiteOptBoxpTest.java
  checker/src/test/java/tests/NullnessLiteOptInitTest.java
  checker/src/test/java/tests/NullnessLiteOptInvaTest.java
  checker/src/test/java/tests/NullnessLiteOptMapkTest.java
  checker/tests/nullness-liteoption-boxp/NullnessLiteBoxing1.java
  checker/tests/nullness-liteoption-boxp/NullnessLiteInit1.java
  checker/tests/nullness-liteoption-boxp/NullnessLiteInvalidDataflow1.java
  checker/tests/nullness-liteoption-boxp/NullnessLiteMapKey1.java
  checker/tests/nullness-liteoption-boxp/README
  checker/tests/nullness-liteoption-init/NullnessLiteBoxing1.java
  checker/tests/nullness-liteoption-init/NullnessLiteInit1.java
  checker/tests/nullness-liteoption-init/NullnessLiteInvalidDataflow1.java
  checker/tests/nullness-liteoption-init/NullnessLiteMapKey1.java
  checker/tests/nullness-liteoption-init/README
  checker/tests/nullness-liteoption-inva/NullnessLiteBoxing1.java
  checker/tests/nullness-liteoption-inva/NullnessLiteInit1.java
  checker/tests/nullness-liteoption-inva/NullnessLiteInvalidDataflow1.java
  checker/tests/nullness-liteoption-inva/NullnessLiteMapKey1.java
  checker/tests/nullness-liteoption-inva/README
  checker/tests/nullness-liteoption-mapk/NullnessLiteBoxing1.java
  checker/tests/nullness-liteoption-mapk/NullnessLiteInit1.java
  checker/tests/nullness-liteoption-mapk/NullnessLiteInvalidDataflow1.java
  checker/tests/nullness-liteoption-mapk/NullnessLiteMapKey1.java
  checker/tests/nullness-liteoption-mapk/README
Labels: enhancement

#15 [NullnessLite][BOXP fix] new implementation (nullness_lite_stub used) with added test cases
  checker/src/main/java/org/checkerframework/checker/nullness/NullnessChecker.java
  checker/src/main/java/org/checkerframework/checker/nullness/nullness_lite.astub
  checker/src/test/java/tests/NullnessLiteComRegBoxpTest.java
  checker/tests/nullness-liteoption-comreg-boxp/CommandLineShadowRegBoxpTest.java
  checker/tests/nullness-liteoption-comreg-boxp/README
  checker/tests/nullness-liteoption-comreg-boxp/stub1.astub
  checker/tests/nullness-liteoption-comreg-boxp/stub2.astub
  checker/tests/nullness-liteoption-comreg/CommandLineShadowRegTest.java
Labels: enhancement
